services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fittracker-backend
    ports:
      - '5001:5000'
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: fittracker-db
    environment:
      POSTGRES_USER: fittrackeradmin
      POSTGRES_PASSWORD: fittrackeradmin
      POSTGRES_DB: fittracker-local
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: fittracker-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fittracker-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fittracker.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres_data:
  redis_data:
